/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as BulkExportRouteImport } from './routes/bulk-export'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VouchersNewRouteImport } from './routes/vouchers.new'
import { Route as VouchersIdRouteImport } from './routes/vouchers.$id'
import { Route as StatementsNewRouteImport } from './routes/statements.new'
import { Route as StatementsIdRouteImport } from './routes/statements.$id'
import { Route as InvoicesNewRouteImport } from './routes/invoices.new'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'
import { Route as AccountsIdRouteImport } from './routes/accounts.$id'
import { Route as InvoicesIdBalanceDueRouteImport } from './routes/invoices.$id.balance-due'
import { Route as AccountsIdConsolidatedRouteImport } from './routes/accounts.$id.consolidated'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkExportRoute = BulkExportRouteImport.update({
  id: '/bulk-export',
  path: '/bulk-export',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VouchersNewRoute = VouchersNewRouteImport.update({
  id: '/vouchers/new',
  path: '/vouchers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VouchersIdRoute = VouchersIdRouteImport.update({
  id: '/vouchers/$id',
  path: '/vouchers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementsNewRoute = StatementsNewRouteImport.update({
  id: '/statements/new',
  path: '/statements/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementsIdRoute = StatementsIdRouteImport.update({
  id: '/statements/$id',
  path: '/statements/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountsRoute,
} as any)
const InvoicesIdBalanceDueRoute = InvoicesIdBalanceDueRouteImport.update({
  id: '/balance-due',
  path: '/balance-due',
  getParentRoute: () => InvoicesIdRoute,
} as any)
const AccountsIdConsolidatedRoute = AccountsIdConsolidatedRouteImport.update({
  id: '/consolidated',
  path: '/consolidated',
  getParentRoute: () => AccountsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/bulk-export': typeof BulkExportRoute
  '/clients': typeof ClientsRoute
  '/documents': typeof DocumentsRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/templates': typeof TemplatesRoute
  '/accounts/$id': typeof AccountsIdRouteWithChildren
  '/invoices/$id': typeof InvoicesIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/statements/$id': typeof StatementsIdRoute
  '/statements/new': typeof StatementsNewRoute
  '/vouchers/$id': typeof VouchersIdRoute
  '/vouchers/new': typeof VouchersNewRoute
  '/accounts/$id/consolidated': typeof AccountsIdConsolidatedRoute
  '/invoices/$id/balance-due': typeof InvoicesIdBalanceDueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/bulk-export': typeof BulkExportRoute
  '/clients': typeof ClientsRoute
  '/documents': typeof DocumentsRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/templates': typeof TemplatesRoute
  '/accounts/$id': typeof AccountsIdRouteWithChildren
  '/invoices/$id': typeof InvoicesIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/statements/$id': typeof StatementsIdRoute
  '/statements/new': typeof StatementsNewRoute
  '/vouchers/$id': typeof VouchersIdRoute
  '/vouchers/new': typeof VouchersNewRoute
  '/accounts/$id/consolidated': typeof AccountsIdConsolidatedRoute
  '/invoices/$id/balance-due': typeof InvoicesIdBalanceDueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/bulk-export': typeof BulkExportRoute
  '/clients': typeof ClientsRoute
  '/documents': typeof DocumentsRoute
  '/settings': typeof SettingsRoute
  '/suppliers': typeof SuppliersRoute
  '/templates': typeof TemplatesRoute
  '/accounts/$id': typeof AccountsIdRouteWithChildren
  '/invoices/$id': typeof InvoicesIdRouteWithChildren
  '/invoices/new': typeof InvoicesNewRoute
  '/statements/$id': typeof StatementsIdRoute
  '/statements/new': typeof StatementsNewRoute
  '/vouchers/$id': typeof VouchersIdRoute
  '/vouchers/new': typeof VouchersNewRoute
  '/accounts/$id/consolidated': typeof AccountsIdConsolidatedRoute
  '/invoices/$id/balance-due': typeof InvoicesIdBalanceDueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/bulk-export'
    | '/clients'
    | '/documents'
    | '/settings'
    | '/suppliers'
    | '/templates'
    | '/accounts/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/statements/$id'
    | '/statements/new'
    | '/vouchers/$id'
    | '/vouchers/new'
    | '/accounts/$id/consolidated'
    | '/invoices/$id/balance-due'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/bulk-export'
    | '/clients'
    | '/documents'
    | '/settings'
    | '/suppliers'
    | '/templates'
    | '/accounts/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/statements/$id'
    | '/statements/new'
    | '/vouchers/$id'
    | '/vouchers/new'
    | '/accounts/$id/consolidated'
    | '/invoices/$id/balance-due'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/bulk-export'
    | '/clients'
    | '/documents'
    | '/settings'
    | '/suppliers'
    | '/templates'
    | '/accounts/$id'
    | '/invoices/$id'
    | '/invoices/new'
    | '/statements/$id'
    | '/statements/new'
    | '/vouchers/$id'
    | '/vouchers/new'
    | '/accounts/$id/consolidated'
    | '/invoices/$id/balance-due'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  BulkExportRoute: typeof BulkExportRoute
  ClientsRoute: typeof ClientsRoute
  DocumentsRoute: typeof DocumentsRoute
  SettingsRoute: typeof SettingsRoute
  SuppliersRoute: typeof SuppliersRoute
  TemplatesRoute: typeof TemplatesRoute
  InvoicesIdRoute: typeof InvoicesIdRouteWithChildren
  InvoicesNewRoute: typeof InvoicesNewRoute
  StatementsIdRoute: typeof StatementsIdRoute
  StatementsNewRoute: typeof StatementsNewRoute
  VouchersIdRoute: typeof VouchersIdRoute
  VouchersNewRoute: typeof VouchersNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-export': {
      id: '/bulk-export'
      path: '/bulk-export'
      fullPath: '/bulk-export'
      preLoaderRoute: typeof BulkExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vouchers/new': {
      id: '/vouchers/new'
      path: '/vouchers/new'
      fullPath: '/vouchers/new'
      preLoaderRoute: typeof VouchersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vouchers/$id': {
      id: '/vouchers/$id'
      path: '/vouchers/$id'
      fullPath: '/vouchers/$id'
      preLoaderRoute: typeof VouchersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statements/new': {
      id: '/statements/new'
      path: '/statements/new'
      fullPath: '/statements/new'
      preLoaderRoute: typeof StatementsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statements/$id': {
      id: '/statements/$id'
      path: '/statements/$id'
      fullPath: '/statements/$id'
      preLoaderRoute: typeof StatementsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/invoices/$id/balance-due': {
      id: '/invoices/$id/balance-due'
      path: '/balance-due'
      fullPath: '/invoices/$id/balance-due'
      preLoaderRoute: typeof InvoicesIdBalanceDueRouteImport
      parentRoute: typeof InvoicesIdRoute
    }
    '/accounts/$id/consolidated': {
      id: '/accounts/$id/consolidated'
      path: '/consolidated'
      fullPath: '/accounts/$id/consolidated'
      preLoaderRoute: typeof AccountsIdConsolidatedRouteImport
      parentRoute: typeof AccountsIdRoute
    }
  }
}

interface AccountsIdRouteChildren {
  AccountsIdConsolidatedRoute: typeof AccountsIdConsolidatedRoute
}

const AccountsIdRouteChildren: AccountsIdRouteChildren = {
  AccountsIdConsolidatedRoute: AccountsIdConsolidatedRoute,
}

const AccountsIdRouteWithChildren = AccountsIdRoute._addFileChildren(
  AccountsIdRouteChildren,
)

interface AccountsRouteChildren {
  AccountsIdRoute: typeof AccountsIdRouteWithChildren
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsIdRoute: AccountsIdRouteWithChildren,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface InvoicesIdRouteChildren {
  InvoicesIdBalanceDueRoute: typeof InvoicesIdBalanceDueRoute
}

const InvoicesIdRouteChildren: InvoicesIdRouteChildren = {
  InvoicesIdBalanceDueRoute: InvoicesIdBalanceDueRoute,
}

const InvoicesIdRouteWithChildren = InvoicesIdRoute._addFileChildren(
  InvoicesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
  BulkExportRoute: BulkExportRoute,
  ClientsRoute: ClientsRoute,
  DocumentsRoute: DocumentsRoute,
  SettingsRoute: SettingsRoute,
  SuppliersRoute: SuppliersRoute,
  TemplatesRoute: TemplatesRoute,
  InvoicesIdRoute: InvoicesIdRouteWithChildren,
  InvoicesNewRoute: InvoicesNewRoute,
  StatementsIdRoute: StatementsIdRoute,
  StatementsNewRoute: StatementsNewRoute,
  VouchersIdRoute: VouchersIdRoute,
  VouchersNewRoute: VouchersNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
